vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        medias:
            uri_prefix: /default.storage
            upload_destination: 'default.storage'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
